
/* Represents the Keys on a Keyboard -----------------------------------------------------------------------------*/
DROP TABLE IF EXISTS [Key];
CREATE TABLE [Key] (
    [Name]        STRING,
    [Code]        INTEGER PRIMARY KEY,
    [Description] STRING
);

CREATE INDEX [Key_indexed] ON Key(Name);

-- https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx
/* Load default key values ---------------------------------------------------------------------------------------*/
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       0,   'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       1,   'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       2,   'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       3,   'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       4,   'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       5,   'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       6,   'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       7,   'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('Backspace',          8,   'The BACKSPACE key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Tab',                9,   'The TAB key');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       10,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       11,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('Clear',              12,  'The CLEAR key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Enter',              13,  'The ENTER key');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       14,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       15,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       16,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       17,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       18,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('Pause',              19,  'The PAUSE key');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       20,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       21,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       22,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       23,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       24,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       25,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       26,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('Escape',             27,  'The ESC (ESCAPE) key');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       28,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       29,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       30,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       31,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('Spacebar',           32,  'The SPACEBAR key');
INSERT INTO [Key](Name,Code,Description) VALUES ('PageUp',             33,  'The PAGE UP key');
INSERT INTO [Key](Name,Code,Description) VALUES ('PageDown',           34,  'The PAGE DOWN key');
INSERT INTO [Key](Name,Code,Description) VALUES ('End',                35,  'The END key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Home',               36,  'The HOME key');
INSERT INTO [Key](Name,Code,Description) VALUES ('LeftArrow',          37,  'The LEFT ARROW key');
INSERT INTO [Key](Name,Code,Description) VALUES ('UpArrow',            38,  'The UP ARROW key');
INSERT INTO [Key](Name,Code,Description) VALUES ('RightArrow',         39,  'The RIGHT ARROW key');
INSERT INTO [Key](Name,Code,Description) VALUES ('DownArrow',          40,  'The DOWN ARROW key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Select',             41,  'The SELECT key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Print',              42,  'The PRINT key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Execute',            43,  'The EXECUTE key');
INSERT INTO [Key](Name,Code,Description) VALUES ('PrintScreen',        44,  'The PRINT SCREEN key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Insert',             45,  'The INS (INSERT) key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Delete',             46,  'The DEL (DELETE) key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Help',               47,  'The HELP key');
INSERT INTO [Key](Name,Code,Description) VALUES ('D0',                 48,  'The 0 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('D1',                 49,  'The 1 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('D2',                 50,  'The 2 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('D3',                 51,  'The 3 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('D4',                 52,  'The 4 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('D5',                 53,  'The 5 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('D6',                 54,  'The 6 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('D7',                 55,  'The 7 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('D8',                 56,  'The 8 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('D9',                 57,  'The 9 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       58,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       59,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       60,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       61,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       62,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       63,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       64,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('A',                  65,  'The A key');
INSERT INTO [Key](Name,Code,Description) VALUES ('B',                  66,  'The B key');
INSERT INTO [Key](Name,Code,Description) VALUES ('C',                  67,  'The C key');
INSERT INTO [Key](Name,Code,Description) VALUES ('D',                  68,  'The D key');
INSERT INTO [Key](Name,Code,Description) VALUES ('E',                  69,  'The E key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F',                  70,  'The F key');
INSERT INTO [Key](Name,Code,Description) VALUES ('G',                  71,  'The G key');
INSERT INTO [Key](Name,Code,Description) VALUES ('H',                  72,  'The H key');
INSERT INTO [Key](Name,Code,Description) VALUES ('I',                  73,  'The I key');
INSERT INTO [Key](Name,Code,Description) VALUES ('J',                  74,  'The J key');
INSERT INTO [Key](Name,Code,Description) VALUES ('K',                  75,  'The K key');
INSERT INTO [Key](Name,Code,Description) VALUES ('L',                  76,  'The L key');
INSERT INTO [Key](Name,Code,Description) VALUES ('M',                  77,  'The M key');
INSERT INTO [Key](Name,Code,Description) VALUES ('N',                  78,  'The N key');
INSERT INTO [Key](Name,Code,Description) VALUES ('O',                  79,  'The O key');
INSERT INTO [Key](Name,Code,Description) VALUES ('P',                  80,  'The P key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Q',                  81,  'The Q key');
INSERT INTO [Key](Name,Code,Description) VALUES ('R',                  82,  'The R key');
INSERT INTO [Key](Name,Code,Description) VALUES ('S',                  83,  'The S key');
INSERT INTO [Key](Name,Code,Description) VALUES ('T',                  84,  'The T key');
INSERT INTO [Key](Name,Code,Description) VALUES ('U',                  85,  'The U key');
INSERT INTO [Key](Name,Code,Description) VALUES ('V',                  86,  'The V key');
INSERT INTO [Key](Name,Code,Description) VALUES ('W',                  87,  'The W key');
INSERT INTO [Key](Name,Code,Description) VALUES ('X',                  88,  'The X key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Y',                  89,  'The Y key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Z',                  90,  'The Z key');
INSERT INTO [Key](Name,Code,Description) VALUES ('LeftWindows',        91,  'The left Windows logo key (Microsoft Natural Keyboard )');
INSERT INTO [Key](Name,Code,Description) VALUES ('RightWindows',       92,  'The right Windows logo key (Microsoft Natural Keyboard)');
INSERT INTO [Key](Name,Code,Description) VALUES ('Applications',       93,  'The Application key (Microsoft Natural Keyboard)');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       94,  'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('Sleep',              95,  'The Computer Sleep key');
INSERT INTO [Key](Name,Code,Description) VALUES ('NumPad0',            96,  'The 0 key on the numeric keypad');
INSERT INTO [Key](Name,Code,Description) VALUES ('NumPad1',            97,  'The 1 key on the numeric keypad');
INSERT INTO [Key](Name,Code,Description) VALUES ('NumPad2',            98,  'The 2 key on the numeric keypad');
INSERT INTO [Key](Name,Code,Description) VALUES ('NumPad3',            99,  'The 3 key on the numeric keypad');
INSERT INTO [Key](Name,Code,Description) VALUES ('NumPad4',            100, 'The 4 key on the numeric keypad');
INSERT INTO [Key](Name,Code,Description) VALUES ('NumPad5',            101, 'The 5 key on the numeric keypad');
INSERT INTO [Key](Name,Code,Description) VALUES ('NumPad6',            102, 'The 6 key on the numeric keypad');
INSERT INTO [Key](Name,Code,Description) VALUES ('NumPad7',            103, 'The 7 key on the numeric keypad');
INSERT INTO [Key](Name,Code,Description) VALUES ('NumPad8',            104, 'The 8 key on the numeric keypad');
INSERT INTO [Key](Name,Code,Description) VALUES ('NumPad9',            105, 'The 9 key on the numeric keypad');
INSERT INTO [Key](Name,Code,Description) VALUES ('Multiply',           106, 'The Multiply key (the multiplication key on the numeric keypad)');
INSERT INTO [Key](Name,Code,Description) VALUES ('Add',                107, 'The Add key (the addition key on the numeric keypad)');
INSERT INTO [Key](Name,Code,Description) VALUES ('Separator',          108, 'The Separator key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Subtract',           109, 'The Subtract key (the subtraction key on the numeric keypad)');
INSERT INTO [Key](Name,Code,Description) VALUES ('Decimal',            110, 'The Decimal key (the decimal key on the numeric keypad)');
INSERT INTO [Key](Name,Code,Description) VALUES ('Divide',             111, 'The Divide key (the division key on the numeric keypad)');
INSERT INTO [Key](Name,Code,Description) VALUES ('F1',                 112, 'The F1 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F2',                 113, 'The F2 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F3',                 114, 'The F3 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F4',                 115, 'The F4 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F5',                 116, 'The F5 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F6',                 117, 'The F6 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F7',                 118, 'The F7 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F8',                 119, 'The F8 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F9',                 120, 'The F9 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F10',                121, 'The F10 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F11',                122, 'The F11 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F12',                123, 'The F12 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F13',                124, 'The F13 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F14',                125, 'The F14 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F15',                126, 'The F15 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F16',                127, 'The F16 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F17',                128, 'The F17 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F18',                129, 'The F18 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F19',                130, 'The F19 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F20',                131, 'The F20 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F21',                132, 'The F21 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F22',                133, 'The F22 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F23',                134, 'The F23 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('F24',                135, 'The F24 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       136, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       137, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       138, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       139, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       140, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       141, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       142, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       143, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       144, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       145, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       146, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       147, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       148, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       149, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       150, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       151, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       152, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       153, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       154, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       155, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       156, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       157, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       158, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       159, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       160, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       161, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       162, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       163, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       164, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       165, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('BrowserBack',        166, 'The Browser Back key');
INSERT INTO [Key](Name,Code,Description) VALUES ('BrowserForward',     167, 'The Browser Forward key');
INSERT INTO [Key](Name,Code,Description) VALUES ('BrowserRefresh',     168, 'The Browser Refresh key');
INSERT INTO [Key](Name,Code,Description) VALUES ('BrowserStop',        169, 'The Browser Stop key');
INSERT INTO [Key](Name,Code,Description) VALUES ('BrowserSearch',      170, 'The Browser Search key');
INSERT INTO [Key](Name,Code,Description) VALUES ('BrowserFavorites',   171, 'The Browser Favorites key');
INSERT INTO [Key](Name,Code,Description) VALUES ('BrowserHome',        172, 'The Browser Home key');
INSERT INTO [Key](Name,Code,Description) VALUES ('VolumeMute',         173, 'The Volume Mute key (Microsoft Natural Keyboard)');
INSERT INTO [Key](Name,Code,Description) VALUES ('VolumeDown',         174, 'The Volume Down key (Microsoft Natural Keyboard)');
INSERT INTO [Key](Name,Code,Description) VALUES ('VolumeUp',           175, 'The Volume Up key (Microsoft Natural Keyboard)');
INSERT INTO [Key](Name,Code,Description) VALUES ('MediaNext',          176, 'The Media Next Track key');
INSERT INTO [Key](Name,Code,Description) VALUES ('MediaPrevious',      177, 'The Media Previous Track key');
INSERT INTO [Key](Name,Code,Description) VALUES ('MediaStop',          178, 'The Media Stop key');
INSERT INTO [Key](Name,Code,Description) VALUES ('MediaPlay',          179, 'The Media Play/Pause key');
INSERT INTO [Key](Name,Code,Description) VALUES ('LaunchMail',         180, 'The Start Mail key (Microsoft Natural Keyboard)');
INSERT INTO [Key](Name,Code,Description) VALUES ('LaunchMediaSelect',  181, 'The Select Media key (Microsoft Natural Keyboard)');
INSERT INTO [Key](Name,Code,Description) VALUES ('LaunchApp1',         182, 'The Start Application 1 key (Microsoft Natural Keyboard)');
INSERT INTO [Key](Name,Code,Description) VALUES ('LaunchApp2',         183, 'The Start Application 2 key (Microsoft Natural Keyboard)');
INSERT INTO [Key](Name,Code,Description) VALUES ('Oem1',               186, 'The OEM 1 key (OEM specific)');
INSERT INTO [Key](Name,Code,Description) VALUES ('OemPlus',            187, 'The OEM Plus key on any country/region keyboard');
INSERT INTO [Key](Name,Code,Description) VALUES ('OemComma',           188, 'The OEM Comma key on any country/region keyboard');
INSERT INTO [Key](Name,Code,Description) VALUES ('OemMinus',           189, 'The OEM Minus key on any country/region keyboard');
INSERT INTO [Key](Name,Code,Description) VALUES ('OemPeriod',          190, 'The OEM Period key on any country/region keyboard');
INSERT INTO [Key](Name,Code,Description) VALUES ('Oem2',               191, 'The OEM 2 key (OEM specific)');
INSERT INTO [Key](Name,Code,Description) VALUES ('Oem3',               192, 'The OEM 3 key (OEM specific)');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       193, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       194, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       195, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       196, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       197, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       198, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       199, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       200, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       201, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       202, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       203, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       204, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       205, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       206, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       207, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       208, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       209, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       210, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       211, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       212, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       213, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       214, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       215, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       216, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       217, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       218, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('Oem4',               219, 'The OEM 4 key (OEM specific)');
INSERT INTO [Key](Name,Code,Description) VALUES ('Oem5',               220, 'The OEM 5 (OEM specific)');
INSERT INTO [Key](Name,Code,Description) VALUES ('Oem6',               221, 'The OEM 6 key (OEM specific)');
INSERT INTO [Key](Name,Code,Description) VALUES ('Oem7',               222, 'The OEM 7 key (OEM specific)');
INSERT INTO [Key](Name,Code,Description) VALUES ('Oem8',               223, 'The OEM 8 key (OEM specific)');
INSERT INTO [Key](Name,Code,Description) VALUES ('Oem102',             226, 'The OEM 102 key (OEM specific)');
INSERT INTO [Key](Name,Code,Description) VALUES ('Process',            229, 'The IME PROCESS key');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       230, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('Packet',             231, 'The PACKET key (used to pass Unicode characters with keystrokes)');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       232, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       233, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       234, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       235, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       236, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       237, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       238, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       239, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       240, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       241, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       242, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       243, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       244, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       245, 'Not assigned');
INSERT INTO [Key](Name,Code,Description) VALUES ('Attention',          246, 'The ATTN key');
INSERT INTO [Key](Name,Code,Description) VALUES ('CrSel',              247, 'The CRSEL (CURSOR SELECT) key');
INSERT INTO [Key](Name,Code,Description) VALUES ('ExSel',              248, 'The EXSEL (EXTEND SELECTION) key');
INSERT INTO [Key](Name,Code,Description) VALUES ('EraseEndOfFile',     249, 'The ERASE EOF key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Play',               250, 'The PLAY key');
INSERT INTO [Key](Name,Code,Description) VALUES ('Zoom',               251, 'The ZOOM key');
INSERT INTO [Key](Name,Code,Description) VALUES ('NoName',             252, 'A constant reserved for future use');
INSERT INTO [Key](Name,Code,Description) VALUES ('Pa1',                253, 'The PA1 key');
INSERT INTO [Key](Name,Code,Description) VALUES ('OemClear',           254, 'The CLEAR key (OEM specific)');
INSERT INTO [Key](Name,Code,Description) VALUES ('(unassigned)',       255, 'Not assigned');

/* Indexes -------------------------------------------------------------------------------------------------------*/
