
/* Represents the Keys on a Keyboard -----------------------------------------------------------------------------*/
DROP TABLE IF EXISTS [Key];
CREATE TABLE [Key] (
    [Name]        STRING,
    [Code]        INTEGER PRIMARY KEY,
    [Description] STRING
);

/* Load default key values ---------------------------------------------------------------------------------------*/
INSERT INTO [Key] VALUES ('Backspace',          8, 'The BACKSPACE key');
INSERT INTO [Key] VALUES ('Tab',                9, 'The TAB key');
INSERT INTO [Key] VALUES ('Clear',             12, 'The CLEAR key');
INSERT INTO [Key] VALUES ('Enter',             13, 'The ENTER key');
INSERT INTO [Key] VALUES ('Pause',             19, 'The PAUSE key');
INSERT INTO [Key] VALUES ('Escape',            27, 'The ESC (ESCAPE) key');
INSERT INTO [Key] VALUES ('Spacebar',          32, 'The SPACEBAR key');
INSERT INTO [Key] VALUES ('PageUp',            33, 'The PAGE UP key');
INSERT INTO [Key] VALUES ('PageDown',          34, 'The PAGE DOWN key');
INSERT INTO [Key] VALUES ('End',               35, 'The END key');
INSERT INTO [Key] VALUES ('Home',              36, 'The HOME key');
INSERT INTO [Key] VALUES ('LeftArrow',         37, 'The LEFT ARROW key');
INSERT INTO [Key] VALUES ('UpArrow',           38, 'The UP ARROW key');
INSERT INTO [Key] VALUES ('RightArrow',        39, 'The RIGHT ARROW key');
INSERT INTO [Key] VALUES ('DownArrow',         40, 'The DOWN ARROW key');
INSERT INTO [Key] VALUES ('Select',            41, 'The SELECT key');
INSERT INTO [Key] VALUES ('Print',             42, 'The PRINT key');
INSERT INTO [Key] VALUES ('Execute',           43, 'The EXECUTE key');
INSERT INTO [Key] VALUES ('PrintScreen',       44, 'The PRINT SCREEN key');
INSERT INTO [Key] VALUES ('Insert',            45, 'The INS (INSERT) key');
INSERT INTO [Key] VALUES ('Delete',            46, 'The DEL (DELETE) key');
INSERT INTO [Key] VALUES ('Help',              47, 'The HELP key');
INSERT INTO [Key] VALUES ('D0',                48, 'The 0 key');
INSERT INTO [Key] VALUES ('D1',                49, 'The 1 key');
INSERT INTO [Key] VALUES ('D2',                50, 'The 2 key');
INSERT INTO [Key] VALUES ('D3',                51, 'The 3 key');
INSERT INTO [Key] VALUES ('D4',                52, 'The 4 key');
INSERT INTO [Key] VALUES ('D5',                53, 'The 5 key');
INSERT INTO [Key] VALUES ('D6',                54, 'The 6 key');
INSERT INTO [Key] VALUES ('D7',                55, 'The 7 key');
INSERT INTO [Key] VALUES ('D8',                56, 'The 8 key');
INSERT INTO [Key] VALUES ('D9',                57, 'The 9 key');
INSERT INTO [Key] VALUES ('A',                 65, 'The A key');
INSERT INTO [Key] VALUES ('B',                 66, 'The B key');
INSERT INTO [Key] VALUES ('C',                 67, 'The C key');
INSERT INTO [Key] VALUES ('D',                 68, 'The D key');
INSERT INTO [Key] VALUES ('E',                 69, 'The E key');
INSERT INTO [Key] VALUES ('F',                 70, 'The F key');
INSERT INTO [Key] VALUES ('G',                 71, 'The G key');
INSERT INTO [Key] VALUES ('H',                 72, 'The H key');
INSERT INTO [Key] VALUES ('I',                 73, 'The I key');
INSERT INTO [Key] VALUES ('J',                 74, 'The J key');
INSERT INTO [Key] VALUES ('K',                 75, 'The K key');
INSERT INTO [Key] VALUES ('L',                 76, 'The L key');
INSERT INTO [Key] VALUES ('M',                 77, 'The M key');
INSERT INTO [Key] VALUES ('N',                 78, 'The N key');
INSERT INTO [Key] VALUES ('O',                 79, 'The O key');
INSERT INTO [Key] VALUES ('P',                 80, 'The P key');
INSERT INTO [Key] VALUES ('Q',                 81, 'The Q key');
INSERT INTO [Key] VALUES ('R',                 82, 'The R key');
INSERT INTO [Key] VALUES ('S',                 83,  'The S key');
INSERT INTO [Key] VALUES ('T',                 84, 'The T key');
INSERT INTO [Key] VALUES ('U',                 85, 'The U key');
INSERT INTO [Key] VALUES ('V',                 86, 'The V key');
INSERT INTO [Key] VALUES ('W',                 87, 'The W key');
INSERT INTO [Key] VALUES ('X',                 88, 'The X key');
INSERT INTO [Key] VALUES ('Y',                 89, 'The Y key');
INSERT INTO [Key] VALUES ('Z',                 90, 'The Z key');
INSERT INTO [Key] VALUES ('LeftWindows',       91, 'The left Windows logo key (Microsoft Natural Keyboard )');
INSERT INTO [Key] VALUES ('RightWindows',      92, 'The right Windows logo key (Microsoft Natural Keyboard)');
INSERT INTO [Key] VALUES ('Applications',      93, 'The Application key (Microsoft Natural Keyboard)');
INSERT INTO [Key] VALUES ('Sleep',             95, 'The Computer Sleep key');
INSERT INTO [Key] VALUES ('NumPad0',           96, 'The 0 key on the numeric keypad');
INSERT INTO [Key] VALUES ('NumPad1',           97, 'The 1 key on the numeric keypad');
INSERT INTO [Key] VALUES ('NumPad2',           98, 'The 2 key on the numeric keypad');
INSERT INTO [Key] VALUES ('NumPad3',           99, 'The 3 key on the numeric keypad');
INSERT INTO [Key] VALUES ('NumPad4',           100,'The 4 key on the numeric keypad');
INSERT INTO [Key] VALUES ('NumPad5',           101,'The 5 key on the numeric keypad');
INSERT INTO [Key] VALUES ('NumPad6',           102,'The 6 key on the numeric keypad');
INSERT INTO [Key] VALUES ('NumPad7',           103,'The 7 key on the numeric keypad');
INSERT INTO [Key] VALUES ('NumPad8',           104,'The 8 key on the numeric keypad');
INSERT INTO [Key] VALUES ('NumPad9',           105,'The 9 key on the numeric keypad');
INSERT INTO [Key] VALUES ('Multiply',          106,'The Multiply key (the multiplication key on the numeric keypad)');
INSERT INTO [Key] VALUES ('Add',               107,'The Add key (the addition key on the numeric keypad)');
INSERT INTO [Key] VALUES ('Separator',         108,'The Separator key');
INSERT INTO [Key] VALUES ('Subtract',          109,'The Subtract key (the subtraction key on the numeric keypad)');
INSERT INTO [Key] VALUES ('Decimal',           110,'The Decimal key (the decimal key on the numeric keypad)');
INSERT INTO [Key] VALUES ('Divide',            111,'The Divide key (the division key on the numeric keypad)');
INSERT INTO [Key] VALUES ('F1',                112,'The F1 key');
INSERT INTO [Key] VALUES ('F2',                113,'The F2 key');
INSERT INTO [Key] VALUES ('F3',                114,'The F3 key');
INSERT INTO [Key] VALUES ('F4',                115,'The F4 key');
INSERT INTO [Key] VALUES ('F5',                116,'The F5 key');
INSERT INTO [Key] VALUES ('F6',                117,'The F6 key');
INSERT INTO [Key] VALUES ('F7',                118,'The F7 key');
INSERT INTO [Key] VALUES ('F8',                119,'The F8 key');
INSERT INTO [Key] VALUES ('F9',                120,'The F9 key');
INSERT INTO [Key] VALUES ('F10',               121,'The F10 key');
INSERT INTO [Key] VALUES ('F11',               122,'The F11 key');
INSERT INTO [Key] VALUES ('F12',               123,'The F12 key');
INSERT INTO [Key] VALUES ('F13',               124,'The F13 key');
INSERT INTO [Key] VALUES ('F14',               125,'The F14 key');
INSERT INTO [Key] VALUES ('F15',               126,'The F15 key');
INSERT INTO [Key] VALUES ('F16',               127,'The F16 key');
INSERT INTO [Key] VALUES ('F17',               128,'The F17 key');
INSERT INTO [Key] VALUES ('F18',               129,'The F18 key');
INSERT INTO [Key] VALUES ('F19',               130,'The F19 key');
INSERT INTO [Key] VALUES ('F20',               131,'The F20 key');
INSERT INTO [Key] VALUES ('F21',               132,'The F21 key');
INSERT INTO [Key] VALUES ('F22',               133,'The F22 key');
INSERT INTO [Key] VALUES ('F23',               134,'The F23 key');
INSERT INTO [Key] VALUES ('F24',               135,'The F24 key');
INSERT INTO [Key] VALUES ('BrowserBack',       166,'The Browser Back key');
INSERT INTO [Key] VALUES ('BrowserForward',    167,'The Browser Forward key');
INSERT INTO [Key] VALUES ('BrowserRefresh',    168,'The Browser Refresh key');
INSERT INTO [Key] VALUES ('BrowserStop',       169,'The Browser Stop key');
INSERT INTO [Key] VALUES ('BrowserSearch',     170,'The Browser Search key');
INSERT INTO [Key] VALUES ('BrowserFavorites',  171,'The Browser Favorites key');
INSERT INTO [Key] VALUES ('BrowserHome',       172,'The Browser Home key');
INSERT INTO [Key] VALUES ('VolumeMute',        173,'The Volume Mute key (Microsoft Natural Keyboard)');
INSERT INTO [Key] VALUES ('VolumeDown',        174,'The Volume Down key (Microsoft Natural Keyboard)');
INSERT INTO [Key] VALUES ('VolumeUp',          175,'The Volume Up key (Microsoft Natural Keyboard)');
INSERT INTO [Key] VALUES ('MediaNext',         176,'The Media Next Track key');
INSERT INTO [Key] VALUES ('MediaPrevious',     177,'The Media Previous Track key');
INSERT INTO [Key] VALUES ('MediaStop',         178,'The Media Stop key');
INSERT INTO [Key] VALUES ('MediaPlay',         179,'The Media Play/Pause key');
INSERT INTO [Key] VALUES ('LaunchMail',        180,'The Start Mail key (Microsoft Natural Keyboard)');
INSERT INTO [Key] VALUES ('LaunchMediaSelect', 181,'The Select Media key (Microsoft Natural Keyboard)');
INSERT INTO [Key] VALUES ('LaunchApp1',        182,'The Start Application 1 key (Microsoft Natural Keyboard)');
INSERT INTO [Key] VALUES ('LaunchApp2',        183,'The Start Application 2 key (Microsoft Natural Keyboard)');
INSERT INTO [Key] VALUES ('Oem1',              186,'The OEM 1 key (OEM specific)');
INSERT INTO [Key] VALUES ('OemPlus',           187,'The OEM Plus key on any country/region keyboard');
INSERT INTO [Key] VALUES ('OemComma',          188,'The OEM Comma key on any country/region keyboard');
INSERT INTO [Key] VALUES ('OemMinus',          189,'The OEM Minus key on any country/region keyboard');
INSERT INTO [Key] VALUES ('OemPeriod',         190,'The OEM Period key on any country/region keyboard');
INSERT INTO [Key] VALUES ('Oem2',              191,'The OEM 2 key (OEM specific)');
INSERT INTO [Key] VALUES ('Oem3',              192,'The OEM 3 key (OEM specific)');
INSERT INTO [Key] VALUES ('Oem4',              219,'The OEM 4 key (OEM specific)');
INSERT INTO [Key] VALUES ('Oem5',              220,'The OEM 5 (OEM specific)');
INSERT INTO [Key] VALUES ('Oem6',              221,'The OEM 6 key (OEM specific)');
INSERT INTO [Key] VALUES ('Oem7',              222,'The OEM 7 key (OEM specific)');
INSERT INTO [Key] VALUES ('Oem8',              223,'The OEM 8 key (OEM specific)');
INSERT INTO [Key] VALUES ('Oem102',            226,'The OEM 102 key (OEM specific)');
INSERT INTO [Key] VALUES ('Process',           229,'The IME PROCESS key');
INSERT INTO [Key] VALUES ('Packet',            231,'The PACKET key (used to pass Unicode characters with keystrokes)');
INSERT INTO [Key] VALUES ('Attention',         246,'The ATTN key');
INSERT INTO [Key] VALUES ('CrSel',             247,'The CRSEL (CURSOR SELECT) key');
INSERT INTO [Key] VALUES ('ExSel',             248,'The EXSEL (EXTEND SELECTION) key');
INSERT INTO [Key] VALUES ('EraseEndOfFile',    249,'The ERASE EOF key');
INSERT INTO [Key] VALUES ('Play',              250,'The PLAY key');
INSERT INTO [Key] VALUES ('Zoom',              251, 'The ZOOM key');
INSERT INTO [Key] VALUES ('NoName',            252,'A constant reserved for future use');
INSERT INTO [Key] VALUES ('Pa1',               253,'The PA1 key');
INSERT INTO [Key] VALUES ('OemClear',          254,'The CLEAR key (OEM specific)');

/* Indexes -------------------------------------------------------------------------------------------------------*/
CREATE INDEX [Key_indexed] ON Key(Name);
